version: "3.9"
services:
  shell:
    build:
      context: .
      target: dev
    entrypoint: bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./:/src
      - ./afhq:/afhq
      - ./checkpoints:/checkpoints
      - ./results:/results
